## 1. Numpy import하기

In [1]:
# numpy패키지를 np라는 별칭으로 가져와서 사용한다
import numpy as np

In [2]:
# import한 패키지의 별칭만 다르게 사용하면
# 모든 파이썬 패키지의 버전을 확인할 수 있다
print(np.__version__)

1.21.5


In [3]:
# !는 리눅스 터미널 명령어를 사용할떄 붙이는 기호이다
!pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.0.0
alabaster                     0.7.12
anaconda-client               1.11.0
anaconda-navigator            2.1.1
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.6.6
astropy                       5.1
asttokens                     2.0.5
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
bin

In [5]:
# 다른 패키지들도 확인해보자
import pandas as pd
import matplotlib
print(matplotlib.__version__)

3.5.3


In [6]:
# 현재 설치된 패키지의 버전들을 requirements.txt로 저장
!pip freeze > reauirements.txt

In [ ]:
# 모든 패키지 설치
! pip install -r requirements.txt

## 2. ndarray 생성하기

In [8]:
arr = np.array([1, 2, 3, 4], dtype = int)
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr0 = np.array([1., 2., 3., 4.])
type(arr0)

numpy.ndarray

In [11]:
type(arr0[0])

numpy.float64

### 2-1. list로부터 생성하기

In [13]:
mylist1 = [1, 2, 3, 4]
mylist2 = [[1, 2, 3, 4],
          [5, 6, 7, 8]]

In [15]:
arr1 = np.array(mylist1)

In [16]:
arr2 = np.array(mylist2)

### 2-2. shape 확인하기

In [17]:
# 4행으로 만들어진 array
arr1.shape

(4,)

In [18]:
# 2행 4열로 만들어진 ndarray
arr2.shape

(2, 4)

## 3. array에서의 data타입

array에서는 list와 다르게 1개의 단일 데이터 타입만 허용

### 3-1. list에서의 data 타입

In [19]:
mylist = [1, 3.14, 'hello', '1234']

In [20]:
type(mylist)

list

In [21]:
mylist

[1, 3.14, 'hello', '1234']

In [22]:
for mem in mylist:
    print(type(mem))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>


In [23]:
mylist[1]

3.14

In [24]:
mylist[3]

'1234'

### 3-2. array에서의 data타입이 혼재된 경우

#### int와 float타입이 섞인 경우

In [25]:
arr = np.array([1, 2, 3, 3.14])

In [26]:
arr

array([1.  , 2.  , 3.  , 3.14])

np함수가 데이터의 손실을 최소화 시키기위해 타입을 실수형으로 알아서 단일화 시킨다.

#### 넘파이의 ndarray는 데이터타입을 하나로 통일한다.

In [28]:
# ndarray의 데이터타입을 확인
for men in arr:
    print(type(mem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


#### int와 float 타입이 섞인 경우, dtype을 지정한 경우

In [29]:
arr = np.array([1, 2, 3, 3.14], dtype = int)
arr

array([1, 2, 3, 3])

#### int와 float, str 타입이 혼재된 경우

In [30]:
arr = np.array([1, 3.14, 'abx', '1234'])
arr

array(['1', '3.14', 'abx', '1234'], dtype='<U32')

데이터 손실을 최소화 하기위해 타입이 문자열로 단일화 되었다.

#### int와 str타입이 혼재된 경우, int로 dtype을 지정한 경우

In [31]:
# 명시적 형변환
temp = '1234'
value = int(temp)
type(value)

int

In [32]:
arr = np.array([1, 3.14, '1234'], dtype = int)
arr

array([   1,    3, 1234])

## 4. 슬라이싱(Sling)

#### 배열의 부분 선택(잘라내기)

In [33]:
# python에서 숫자의 범위 0 ~ 9(10미만)
temp = range(10)
temp
# 리스트형채를 취해야 값이 출력된다
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
# range()함수는 혼자서 리스트를 생성하지 않는다
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [36]:
# python 에서 range함수를 사용하여 list를 생성 할 수 있다
myList = list(range(10))
arr0 = np.array(myList)
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4-1. index를 지정하여 색인

#### 1차원 array

In [37]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[0]

0

In [39]:
arr[5]

5

In [40]:
# 10번째 리스트는 없다. 따라서 out of bounds에러 발생
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [41]:
# -1은 뒤에서부터 첫번째로 계산이 가능하다
arr[-1]

9

In [42]:
arr[-10]

0

In [43]:
# 뒤에서 11번째도 존재하지 않아 오류가 발생
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 array

In [49]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [50]:
arr2d.shape

(3, 4)

In [51]:
# arr2d[행, 열]
arr2d[0, 2]

3

In [52]:
arr2d[2, 1]

10

### 4-2. 범위 색인

#### 1차원

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# index 1이상 끝까지
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# index 5미만 까지
arr[:5]

array([0, 1, 2, 3, 4])

In [55]:
# index1이상 5미만
arr[1:5]

array([1, 2, 3, 4])

#### 2차원

In [57]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [59]:
# row(행)을 모두 가져오라는 경우
# 0행, 모든 열
arr2d[0, :]

array([1, 2, 3, 4])

In [60]:
arr2d[0, :].shape

(4,)

In [61]:
# 모등 행의 2열을 가져오려는 경우
arr2d[:,2]

array([ 3,  7, 11])

In [62]:
# 부분적으로 가져오려는 경우
# 0, 1행과 모든 열
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
# 0, 1행과 2열부터 마지막열까지 
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 5. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용한다.

In [64]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [65]:
# 추출하고 싶은 인덱스를 리스트로 생성
idx = [1, 3, 5]

In [66]:
arr[idx]

array([23,  7, 65])

변수 지정 후 추출도 가능하다.

### 5-1. 2차원 array

In [67]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [68]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 6. Boolean 인덱싱

조건필터링을 통하여 Boolean값을 이용한 색인

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [71]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 6-1. True와 False 값으로 색인하기

In [72]:
myTrueFalse = [True, False, True]

In [73]:
# arr의 갯수만큼 boolean index의 리스트를 생성해줘야 한다
arr[myTrueFalse]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [74]:
arr > 2

array([False, False,  True,  True,  True,  True,  True])

In [75]:
arr[arr > 2]

array([3, 4, 5, 6, 7])

In [76]:
myTrueFalse = [True, False, True, False, True, False, True]

In [77]:
arr[myTrueFalse]

array([1, 3, 5, 7])

### 6-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있다.

In [78]:
# result에는 boolean index배열이 저장된다
result = arr2d > 2
result

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인한다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 된다(꺾쇠 괄호 안에 조건문 삽입)

In [79]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [80]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])

## 7. arange

* array + range = arange

### 7-1. 순서대로 리스트에 값을 생성하려면

In [82]:
# 1 ~ 10까지 값을 생성
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### 파이썬에서 함수의 인수 순서, 인수의 이름을 지정한다는 의미"

In [83]:
def cal(op1, op2, op3):
    return(op1 * op2 + op3)
    # 위와같이 우선연산자가 포함된 경우 값의 순서에 따라 결과값이 달라질 것이다
    # 그러므로 아래 함수에 인수순서를 별도로 지정해서 실행할 수 있다
result = cal(op3 = 3, op2 = 2, op1 = 1)
print(result)

5


### 7-2. arange를 사용해서 쉽게 생성하기

첫번째 인자에는 start이상, 두 번째 인자에는 stop의 미만이 들어간다.

In [84]:
arr = np.arange(start = 11, stop = 1, step = -1)
arr

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

### 7-3. keyword 인자 사용하기

keyword 인자는 파라미터(인자)의 keyword를 지정해줌으로써 순서 없이 지정해 줄 수 있다.

In [85]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr = np.arange(stop = 11, start = 1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 7-4. 홀수의 값만 생성

step 키워드를 활용하여 홀수의 값만 생성해보자

In [88]:
# start,stop,step과 같은 이름을 적지 않을 경우는 반드시 순서를 지켜야 한다.
# np.arange([start,] stop[, step,], dtype=None)
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [89]:
# 다른방법
arr = np.arange(start=1, stop=10, step=2)
arr

array([1, 3, 5, 7, 9])

## 8. 1차원 정렬

In [90]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

* np.sort()

In [91]:
# 오름차순 정렬
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

기본적으로 오름차순 정렬을 수행한다.

In [92]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

내림차순 정렬은 옵션에 -1값을 주면된다. 하지만 이 값들은 유지가 되지 않으므로 배열자체에 sort를 수행한다.

In [93]:
arr2 = np.sort(arr)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [95]:
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 9. N차원 정렬

In [96]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [97]:
arr2d.shape

(3, 4)

### 9-1. 열 정렬(왼쪽에서 오른쪽으로)

In [98]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [99]:
# 가로방향 같은 행 데이터 안에서 정렬
np.sort(arr2d, axis = 1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 9-2. 행 정렬(위에서 아래로)

In [100]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [101]:
# 세로방향 열 데이터간의 정렬
np.sort(arr2d, axis = 0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

## 10. index를 반환하는 argsort

정렬된 값을 반환하는 것이 아닌 index를 반환한다.

In [102]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

### 10-1. 열 정렬(왼쪽에서 오른쪽으로)

In [103]:
# sort해야항 index의 순서를 리턴한다.
np.argsort(arr2d, axis = 1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

### 10-2. 행 정렬(위에서 아래로)

In [104]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [105]:
np.argsort(arr2d, axis = 0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

## 11. 행렬 - 덧셈

### 11-1. 덧셈

In [106]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [107]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [108]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [109]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [110]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [111]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

행과 열의 개수가 다르므로 덧셈계산이 불가능하다.

### 11-2. Sum

In [112]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [113]:
# 세로로 더해준다
np.sum(a, axis = 0)

array([3, 5, 7])

In [114]:
# 가로로 더해준다
np.sum(a, axis = 1)

array([6, 9])

## 12. 행렬 - 뺄셈

In [115]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [116]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [117]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [118]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [119]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [120]:
a - b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

덧셈과 마찬가지로 행과 열이 다르므로 계산이 불가능하다.

## 13. 곱셈

### 일반 곱셈

In [121]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [122]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [123]:
a.shape, b.shape

((2, 3), (2, 3))

In [124]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순곱셈과 dot product는 다른 메커니즘이므로 유의해서 사용한다.

In [125]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [126]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [127]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [128]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [129]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [130]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [131]:
# 행렬 곱 = np.dot()
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [132]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

## 14. Broadcasting

### 14-1. 숫자의 연산(단일)

In [133]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [134]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [135]:
# broadcast의 +연산은 행렬의 모든 요소에 동일한 값을 더한다.
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [136]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [137]:
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [138]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 14-2. array(배열)의 브로드캐스팅

오리지널 array의 shape가 유지됨을 잘 확인해야 한다.

In [139]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [140]:
b = np.array([[1], 
              [2]])

In [141]:
a.shape, b.shape

((2, 3), (2, 1))

In [142]:
b * a

array([[1, 2, 3],
       [4, 6, 8]])

a의 [1, 2, 3]에 1이 각각 곱해지고, a의 [2, 3, 4]에 2가 각각 곱해진다.

In [143]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [144]:
b = np.array([1, 2, 3])

In [145]:
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

### Dict타입을 for문을 사용하여 연습

In [1]:
# 제품명: 가격, 재고
myDict = {'메로나':[300,20],
          '비비빅':[400,3],
          '죠스바':[250, 100]}

In [2]:
# key값만 출력하고 싶을때
for name in myDict.keys():
    print(name)

메로나
비비빅
죠스바


In [3]:
# value값만 출력하고 싶을때
for name in myDict.values():
    print(name)

[300, 20]
[400, 3]
[250, 100]


In [4]:
# key, value값의 요소를 모두 출력하고 싶을때
for key, value in myDict.items():
    print(key, value)

메로나 [300, 20]
비비빅 [400, 3]
죠스바 [250, 100]


In [5]:
# value값의 인덱싱을 하여 출력
for key, value in myDict.items():
    print(key, value[1])

메로나 20
비비빅 3
죠스바 100


## 선형함수 증명하는 함수

### 1. f(x1 + x2) = f(x1) + f(x2)
### 2. f(kx) = kf(x)

#### 선형함수의 여부를 확인할 때 bias항을 빼고 확인하자. bias항을 추가할 경우 함수의 값이 다르게 나타난다.

In [4]:
# y = 2x가 선형함수인지 확인
# f(x)를 구하는 함수

def myFunc(x):
    y = 2*x
    return y

In [7]:
# 선형함수인지 확인하는 함수
def isLinear(x1, x2, k):
    
    cond1 = False
    cond2 = False
    
    result1 = myFunc(x1 + x2)
    result2 = myFunc(x1) + myFunc(x2)
    result3 = myFunc(k*x1)
    result4 = k * myFunc(x1)
    
    if result1 == result2:
        cond1 = True
    
    if result3 == result4:
        cond2 = True
        
    if cond1 and cond2:
        return True
    else:
        return False
    
    
    # 난수를 사용하여 증명한다
import random
counter = 0
for i in range(100):
    x1 = random.randrange(1, 200)
    x2 = random.randrange(10, 300)
    k = random.randrange(1, 20)
        
    result = isLinear(x1, x2, k)
    if result == True:
        # print('함수는 선형함수 입니다')
        counter += 1
    else:
        print('함수는 비선형함수 입니다.')
        break
        
if counter == 100:
    print('함수는 선형함수 입니다.')

함수는 선형함수 입니다.
